database-driver=org.postgresql.Driver
database-url=jdbc:postgresql://localhost/
database-username=postgres
database-password=postgres
webserver-enabled=true
webserver-hostname=127.0.0.1
webserver-port=80